version: '3'

services:
  db:
    image: mysql:8.0.31
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: local
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: 'Asia/Tokyo'
    command: mysqld
    volumes:
      - db-store:/var/lib/mysql
      - ./compose/mysql/logs:/var/log/mysql
      - ./compose/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - 3306:3306
  vis:
    image: registry.hub.docker.com/grafana/grafana-oss:9.2.6
    container_name: grafana
    volumes:
      - ./compose/grafana:/var/lib/grafana
    ports:
      - 3000:3000

# docker compose stores mysql data below
# check docker volume ls 
volumes:
  db-store:
