datasources:
  excel:
    - name: "sample spreadsheet"
      path: "testdata/excel/test.xlsx"
      importer:
        path: "importer/excel/sampleimporter.go"
  jira:
    # JIRA API might be multiple for handling multi projects
    - name: "sample project"
      endpoint: "xxx"
      project: "xxx"
      auth:
        user: xxx
        password: yyyy
      importer:
        path: "importer/jira/sampleimporter.go"
