datasources:
  jira:
    # JIRA API might be multiple for handling multi projects
    - name: "sample project"
      endpoint: "xxx"
      project: "xxx"
      auth:
        method: basic
        user: xxx
        password: yyyy
database:
  type: mysql
  host: localhost
  auth:
    user: root
    password: root
