version: "0.1"
excel:
  # table1
  - path: "./testdata/testdata.xlsx"
    sheet: "Sheet1"
    range:
      leftTopCell: "B2"
      rightBottomCell: "J6"
    columnHeaderFormat: "2006/01"
    rowHeaderFormat: "[a-zA-Z0-9]+"
    columns:
      - name: "Key"
        type: int
jira:
  # JIRA API might be multiple for visualizing multi projects
  - endpoint: "xxx"
    project: "xxx"
    auth:
      user: xxx
      password: yyyy
    import-from: "1M"
