apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: product-measurement
resources:
  - ./namespace.yaml
  - ./mysql.yaml
  - ./grafana.yaml

configMapGenerator:
  - name: grafana-dashboard-scheduling
    files:
      - ../../dashboards/scheduling.json
