apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: mysql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
# replace secrets below when you use in production
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  labels:
    app: mysql
type: Opaque
data:
  rootpassword: cm9vdHBhc3N3b3Jk # rootpassword
  password: cG1wYXNzd29yZA== # pmpassword
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  labels:
    app: mysql
data:
  my.cnf: |
    [mysqld]
    default_authentication_plugin=mysql_native_password

    character-set-server=utf8mb4
    collation-server=utf8mb4_unicode_ci
    explicit_defaults_for_timestamp=1
    long_query_time=1.0
    max_connections=10000
    max_connect_errors=10

    datadir=/var/lib/mysql
    socket=/var/lib/mysql/mysql.sock
    log-error=/var/log/mysql/mysql-error.log
    pid-file=/var/run/mysqld/mysqld.pid

    slow_query_log=1
    slow_query_log_file=/var/log/mysql/mysql-slow.log

    general_log=1
    general_log_file=/var/log/mysql/mysql-query.log

    [mysql]
    default-character-set=utf8mb4
    socket=/var/lib/mysql/mysql.sock

    [client]
    default-character-set=utf8mb4
    socket=/var/lib/mysql/mysql.sock
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - image: mysql:8.0.31
          name: mysql
          ports:
            - containerPort: 3306
              name: mysql
          env:
            - name: MYSQL_DATABASE
              value: product-measurement
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: rootpassword
            - name: MYSQL_USER
              value: pm
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
            - name: mysql-config-volume
              mountPath: /etc/mysql/conf.d/
          resources:
            requests:
              cpu: 250m
              memory: 500Mi
            limits:
              cpu: 1000m
              memory: 1Gi
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim
        - name: mysql-config-volume
          configMap:
            name: mysql-config
