name: push-image
on:
  push:
    branches:
      - main

jobs:
  build-image-publish:
    name: build docker image
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, '[skip ci]') == false
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
          cache: true
      - name: Install dependent packages
        run: go mod download
      - name: publish image with timestamp
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: amasuda/issue2md
          addTimestamp: true
          registry: docker.io # TIPS: hub.docker.com is website and not appropriate
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: publish image with latest tag
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: amasuda/issue2md
          tags: latest
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
